spring.application.name=netadex

# ===============================
# Supabase PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://db.ohavumtltfdefjmmyugz.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=eCPLW4eB8RtOm4de

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ===============================
# Server
# ===============================
server.port=8080